name: CI
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  golangci:
    strategy: 
      matrix:
        go-version: 
        - 1.24.x
    name: lint
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Config Path
        run: "export PATH=$(go env GOPATH)/bin:$PATH"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6.5.0
        with:
          version: latest
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout 5m
  GoSecurity:
    strategy: 
      matrix:
        go-version: [1.24.x]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch Repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          check-latest: true
      - name: Config Path
        run: "export PATH=$(go env GOPATH)/bin:$PATH"
      - name: Install Gosec
        run: "go install github.com/securego/gosec/v2/cmd/gosec@latest"
      - name: Run Gosec
        working-directory: .
        run: "gosec -tests ./..."
      - name: Install govulncheck
        run: "go install golang.org/x/vuln/cmd/govulncheck@latest"
      - name: Run govulncheck
        working-directory: .
        run: "govulncheck ./..."