on: ["push", "pull_request"]

name: Coverage

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v5

    - uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        check-latest: true

    - run: go test -v -coverprofile=profile.cov ./...

    - uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov